### PR TITLE
add rspamd spam filtering system

### PR DESCRIPTION
**Pull request by bleuchtang**
Rspamd called by milter protocol is a lightweight solution for spam filtering with a minimum of configurations. This PR add an option to include these softwares.

### CODE REVIEW

**Comment by drybjed** [comment]
`rspamd` should have its own dedicated role. That way you are able to set up a separate `rspam` host(s) and pass messages between your Postfix servers and mail scanners. This also helps switching `rspamd` to something else if somebody wants, for example Amavis.

I'm not sure about `rmilter`, i think it's closely related to `rspamd`? So it could be in the same role as `rspamd`.

Right now `debops.postfix` lacks a good interface to glue the spam filters together, we would need to look into that.

**Comment by bleuchtang** [comment]
Agree. How can automatically add value in postfix main.cf with an external role ? (see postfix_dependent_maincf param, but maybe there is an better solution )

**Comment by drybjed** [comment]
@bleuchtang Yes, currently using `postfix_dependent_maincf` variable is your best bet. You can check out `debops.mailman` and `debops.smstools` roles to see what can be done with it.

**Comment by le9i0nx** [comment]
@bleuchtang
My version. But frankly this is just the beginning.
https://github.com/le9i0nx/ansible-rspamd

**Comment by bleuchtang** [comment]
@le9i0nx 
Here is mine, it's no more than this PR in a separate repo :)
https://github.com/bleuchtang/ansible-rspamd

**Comment by drybjed** [comment]
After the new version of `debops.postfix` was released, it's now possible to implement `rspamd` support as a separate Ansible role. It should be done as such. I'm closing this issue.

**Pull request closed without merging**
